version: 2
updates:
  - package-ecosystem: "github-actions"
    # Adds .github/workflows automatically
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
